feature: Driver service
alexeyburak/modsen-cab-aggregator pull request #2
Opened 2024-02-01 09:38 UTC by alexeyburak

2024-02-01 10:14 UTC, KirillKostylev requested changes

2024-02-01 10:14 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/cabaggregator/driverservice/repository/DriverRepository.java
> +@Repository
А нужна тут аннотация? Отпиши почему (да или нет)

2024-02-01 10:14 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/cabaggregator/driverservice/service/impl/DriverServiceImpl.java
> +        driver.setStatus(driverDTO.getStatus());
сеттеры можно вынести в отдельный метод

2024-02-01 10:14 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/cabaggregator/driverservice/service/impl/DriverServiceImpl.java
> +    }
DriverService - не самое подходящее место для валидации параметров страницы

2024-02-01 10:23 UTC, alexeyburak commented on driver-service/src/main/java/com/modsen/cabaggregator/driverservice/repository/DriverRepository.java
> +@Repository
для работы репозитория она не обязательна, т.к. он расширяет JpaRepository, но вроде рекомендуется указывать спрингу класс, где происходит работа с моделями

> Spring [@Repository](https://www.digitalocean.com/community/users/repository) annotation is used to indicate that the class provides the mechanism for storage, retrieval, search, update and delete operation on objects.

2024-02-01 10:25 UTC, alexeyburak commented on driver-service/src/main/java/com/modsen/cabaggregator/driverservice/service/impl/DriverServiceImpl.java
> +    }
я планирую создать _common_ либу и там вынесу это в какие-то утилитные классы

2024-02-02 07:42 UTC, KirillKostylev approved these changes

2024-02-02 12:06 UTC, merged